//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolution.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string PayrollNumber { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Telephone { get; set; }
        public int Mobile { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Postcode { get; set; }
        public string Email { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Category { get; set; }

    }
}
